apiVersion: v2
name: merly-mentor
description: Helm chart for Merly Mentor
type: application
version: 1.0.20
appVersion: "v0.16.1"
home: https://www.merly.ai/
sources:
  - https://github.com/merly-ai/mentor-helm-chart
